# syntax=docker/dockerfile:1.7
FROM node:22-alpine

RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

COPY . .
RUN --mount=type=secret,id=packagemaze_npmrc,target=/run/secrets/packagemaze.npmrc \
    corepack enable pnpm && \
    NPM_CONFIG_USERCONFIG=/run/secrets/packagemaze.npmrc pnpm add -g turbo
RUN --mount=type=secret,id=packagemaze_npmrc,target=/run/secrets/packagemaze.npmrc \
    NPM_CONFIG_USERCONFIG=/run/secrets/packagemaze.npmrc pnpm install

EXPOSE 3000
VOLUME [ "/app/node_modules", "/app/web/node_modules" ]
CMD ["pnpm", "dev", "--filter=web"]
