# syntax=docker/dockerfile:1.7
FROM node:22-alpine

RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

COPY . .

RUN --mount=type=secret,id=packagemaze_npmrc,target=/run/secrets/packagemaze.npmrc \
    corepack enable pnpm && \
    NPM_CONFIG_USERCONFIG=/run/secrets/packagemaze.npmrc pnpm add -g turbo
RUN --mount=type=secret,id=packagemaze_npmrc,target=/run/secrets/packagemaze.npmrc \
    NPM_CONFIG_USERCONFIG=/run/secrets/packagemaze.npmrc pnpm install

EXPOSE 3002

ENV VITE_SPACE_BASE_PATH="/spaces"

VOLUME [ "/app/node_modules", "/app/apps/space/node_modules"]

CMD ["pnpm", "dev", "--filter=space"]
